# Generated by Django 5.2.8 on 2025-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('warranty', models.CharField(max_length=10)),
                ('return_or_replacement_policy', models.TextField()),
                ('seller_contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
